export const SOURCES = Object.freeze([
  Object.freeze({
    id: "guardian-uk",
    name: "The Guardian",
    countryCode: "GB",
    countryName: "England / United Kingdom",
    kind: "newspaper",
    homepageUrl: "https://www.theguardian.com/uk",
    feedUrl: "https://www.theguardian.com/uk/rss",
    termsUrl: "https://www.theguardian.com/help/terms-of-service",
    capturePolicy: "official-feed-private-evidence",
    publicContentPolicy: "metadata-and-excerpt",
    active: true,
    notes: "Official RSS feed; full feed captures remain private evidence.",
  }),
  Object.freeze({
    id: "bbc-england",
    name: "BBC News England",
    countryCode: "GB",
    countryName: "England / United Kingdom",
    kind: "public-broadcaster",
    homepageUrl: "https://www.bbc.co.uk/news/england",
    feedUrl: "https://feeds.bbci.co.uk/news/england/rss.xml",
    termsUrl: "https://www.bbc.co.uk/usingthebbc/terms-of-use/#15metadataandrssfeeds",
    capturePolicy: "official-feed-private-evidence",
    publicContentPolicy: "metadata-and-excerpt",
    active: true,
    notes: "Official England RSS feed; bylines are not consistently supplied.",
  }),
  Object.freeze({
    id: "irish-times",
    name: "The Irish Times",
    countryCode: "IE",
    countryName: "Ireland",
    kind: "newspaper",
    homepageUrl: "https://www.irishtimes.com",
    feedUrl: "https://www.irishtimes.com/arc/outboundfeeds/rss/?outputType=xml",
    termsUrl: "https://www.irishtimes.com/policy-and-terms/terms-conditions/",
    capturePolicy: "official-feed-private-evidence",
    publicContentPolicy: "metadata-and-excerpt",
    active: true,
    notes: "Official RSS feed; source-supplied body data is never publicly republished.",
  }),
  Object.freeze({
    id: "rte-news",
    name: "RTÉ News",
    countryCode: "IE",
    countryName: "Ireland",
    kind: "public-broadcaster",
    homepageUrl: "https://www.rte.ie/news/",
    feedUrl: "https://www.rte.ie/feeds/rss/?index=/news/",
    termsUrl: "https://about.rte.ie/terms-and-conditions/",
    capturePolicy: "official-feed-private-evidence",
    publicContentPolicy: "metadata-and-excerpt",
    active: true,
    notes: "Official news RSS feed; public pages show source metadata and excerpts only.",
  }),
]);

export function sourceById(sourceId) {
  return SOURCES.find(({ id }) => id === sourceId) ?? null;
}